
version: '3.3's
services:
  duckdns:
    image: linuxserver/duckdns
    environment:
      - TZ=Europe/Berlin
      - SUBDOMAINS=subdomain
      - TOKEN=your-token
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

