
Was ist Traefik?

Traefik ist ein moderner HTTP-Reverse-Proxy und Load-Balancer, der entwickelt wurde, 
um Bereitstellungen von Microservices zu vereinfachen. Es unterstützt mehrere 
Backends (Docker, Swarm Mode, Kubernetes, Marathon, Consul, Etcd, Rancher, Amazon ECS und viele andere) 
zur Verwaltung seiner Konfiguration automatisch und dynamisch.

Wie funktioniert Traefik?

Traefik verbindet sich mit Ihrem Dienst-Registry oder Orchestrator-API und 
konfiguriert sich selbst automatisch und dynamisch, um eingehenden Verkehr zu Ihren Anwendungen zu routen. 
Das bedeutet, dass Sie Traefik sagen können, dass es auf Ihre Orchestrator-API (z.B. Docker oder Kubernetes) hören soll, 
und es wird automatisch die korrekten Routing-Regeln anwenden, wenn Sie Ihre Anwendungen starten und stoppen.

Traefik kann auch automatisch Let's Encrypt SSL-Zertifikate für Ihre Domains beantragen und erneuern, 
was die Notwendigkeit für manuelle Interventionen zur Konfiguration von SSL-Zertifikaten stark reduziert.

Hier ist ein einfacher Traefik-Stack, den Sie in Portainer verwenden können:

version: "3.3"

services:
  traefik:
    image: traefik:v2.3
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=youremail@example.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /path/to/letsencrypt:/letsencrypt
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true


Bitte beachten Sie, dass Sie Ihre eigene E-Mail-Adresse für youremail@example.com und 
den richtigen Pfad für /path/to/letsencrypt angeben müssen.

Dieser Stack startet Traefik und konfiguriert es so, dass es Docker als Backend-Provider verwendet. 
Es hört auf Port 80 und routet den Verkehr automatisch zu Ihren Docker-Diensten. Es verwendet Let's Encrypt, um 
SSL-Zertifikate zu generieren und zu erneuern und speichert diese Zertifikate im /letsencrypt-Verzeichnis.

Dies ist nur ein einfaches Beispiel. Traefik ist ein sehr mächtiges Werkzeug und seine Konfiguration 
kann stark variieren, abhängig von Ihren spezifischen Anforderungen.

Bitte beachten Sie, dass diese Konfiguration möglicherweise nicht Ihren genauen Anforderungen entspricht und 
angepasst werden muss, um Ihre spezifischen Bedürfnisse zu erfüllen. Es wird auch empfohlen, die Traefik-Dokumentation zu lesen 
und zu verstehen, bevor Sie sie in Ihrer Produktionsumgebung implementieren.



################## Beachten ##########


Der NGINX Proxy Manager ist ein Open-Source-Projekt, das eine webbasierte Benutzeroberfläche 
bereitstellt, um Reverse-Proxy-, SSL-Zertifikat- und Zugriffskontrollregeln in einer NGINX-Umgebung zu verwalten. 
Er ermöglicht es Ihnen, den Datenverkehr zu Ihren Anwendungen zu leiten, die Sicherheit mit SSL-Zertifikaten zu 
erhöhen und Zugriffssteuerungsregeln zu definieren.

Im Kontext Ihres Docker Swarm Clusters können Sie den NGINX Proxy Manager verwenden, um den Verkehr zu 
Ihren Diensten basierend auf dem Hostnamen (z.B. subdomain.yourdomain.com) oder dem Pfad (z.B. yourdomain.com/myapp) zu routen. 
Sie können auch SSL-Zertifikate für Ihre Domains mit Let's Encrypt direkt aus der Benutzeroberfläche des NGINX Proxy Managers anfordern und erneuern.

Die grundlegende Nutzung des NGINX Proxy Manager beinhaltet im Allgemeinen die folgenden Schritte:

1. Einrichten und Starten des NGINX Proxy Manager-Dienstes in Ihrem Docker Swarm Cluster. Dies umfasst in der Regel die Bereitstellung 
eines Docker-Stacks, der den NGINX Proxy Manager, eine Datenbank (normalerweise MariaDB oder MySQL) und alle benötigten Volumes und Netzwerke enthält.

2. Anmelden am NGINX Proxy Manager über die webbasierte Benutzeroberfläche (standardmäßig verfügbar auf Port 81).

3. Hinzufügen von Proxy-Hosts in der NGINX Proxy Manager-Oberfläche. Jeder Proxy-Host repräsentiert eine Regel, 
die eingehenden Verkehr basierend auf dem Hostnamen oder Pfad an einen Ihrer Dienste weiterleitet. Beim Hinzufügen eines Proxy-Hosts können 
Sie auch SSL-Zertifikate anfordern und erneuern und Zugriffssteuerungsregeln definieren.

Bitte beachten Sie, dass sowohl Traefik als auch der NGINX Proxy Manager ähnliche Funktionen bieten und Sie in den 
meisten Fällen nicht beide gleichzeitig in der gleichen Umgebung benötigen. Beide Tools ermöglichen es Ihnen, den Verkehr zu Ihren Diensten zu 
routen und SSL-Zertifikate zu verwalten. Die Wahl zwischen den beiden hängt in erster Linie von Ihren spezifischen 
Anforderungen und Ihrer Vertrautheit mit den jeweiligen Tools ab.





